/**
 * Builds rich descriptions and verified tables of contents for each readable book in
 * data/catalog / BOOKS_LIST, for the preview modal on /written.
 *
 * Source of truth: data/sources/books/combined_toc_master.md and high-resolution OCR.
 *
 * Output: data/catalog/book-previews.json
 * Run:    node scripts/generate/generate_book_previews.mjs
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const MASTER = path.join(ROOT, 'public', 'data', 'generated_indices', 'MASTER_INDEX.json');
const OUT = path.join(ROOT, 'data', 'catalog', 'book-previews.json');

const MASTER_TOCS = {
    'salat-booklet': [
        { title: 'The Contact Prayers [Salat]', page: 1 },
        { title: 'Abraham: Original Source of the Contact Prayers', page: 2 },
        { title: 'The Correct Azaan', page: 3 },
        { title: 'Preparation for the Contact Prayer (The Ablution)', page: 3 },
        { title: 'HOW TO PERFORM THE CONTACT PRAYERS', page: 4 },
        { title: 'Reciting "The Key"', page: 5 },
        { title: 'The Prostration Position (Sujood)', page: 6 },
        { title: 'The Daily Prayers (Dawn, Noon, Afternoon, Sunset, Night)', page: 7 },
        { title: 'The Group & Friday Prayer', page: 8 },
    ],
    'perpetual-miracle': [
        { title: 'THE PERPETUAL MIRACLE OF MUHAMMAD (peace be upon him)', page: 1 },
        { title: 'If all the humans and all jinn', page: 2 },
        { title: 'None of us witnessed Moses when he turned his staff into a serpent', page: 3 },
        { title: 'as Pharaoh, the magicians, and the Israelites witnessed the miracles of Moses', page: 4 },
        { title: "Abdul-Baqi, and published by the People's Press", page: 5 },
        { title: 'This is of course what all the non-Muslims claim', page: 6 },
        { title: "THE ONLY POSSIBLE EXPLANATION LEFT is that a SUPER BEING did write the Qur'an", page: 7 },
        { title: 'person will have the number 19 imposed on him', page: 8 },
        { title: 'A historical fact that supports the identification of the number 19', page: 9 },
        { title: 'overwhelming. Thus, the greater portion of this physical, touchable, examinable', page: 10 },
        { title: 'WHO WOULD KNOW THE ONLY SURAS WHICH CONTAIN EQUAL NUMBERS OF THE LETTER QAF', page: 11 },
        { title: 'beginning of the only 2 suras which contain 57 Qafs each', page: 12 },
        { title: 'Moving on the other Qur’anic initials, let us look at the letter Nun', page: 13 },
        { title: "Thus, every generation of human beings will receive and witness Muhammad's perpetual miracle", page: 14 },
        { title: 'this interlocking system, and see how it is complete beyond human ability', page: 15 },
        { title: "THE QUR'AN MUHAMMAD'S PERPETUAL MIRACLE", page: 16 },
    ],
    'english-meanings-of-the-quran': [
        { title: "English Meanings of the Qur'an : 1", page: 1 },
        { title: 'Surah Al-Fatihah', page: 2 },
        { title: 'COMMENTARY', page: 5 },
        { title: 'Sura Al-Baqarah (The Heifer) 2:1-29', page: 6 },
        { title: 'Surah Al-Baqarah', page: 7 },
        { title: 'Sura Al-Baqarah (2)', page: 13 },
    ],
    'eternity-screenplay': [
        { title: 'ETERNITY - Screenplay', page: 1 },
        { title: 'Page 1 - ETERNITY', page: 4 },
        { title: 'Page 7 - ETERNITY', page: 10 },
        { title: 'Page 22 - ETERNITY', page: 25 },
        { title: 'Page 42 - ETERNITY', page: 45 },
        { title: 'Page 67 - ETERNITY', page: 70 },
        { title: 'Page 89 - ETERNITY', page: 92 },
    ],
    'miracle-of-quran-alphabets': [
        { title: 'About the Author', page: 9 },
        { title: 'Introduction', page: 12 },
        { title: 'Prologue', page: 17 },
        { title: "Chapter 1: Prerequisite Information About The Qur'an", page: 22 },
        { title: "Chapter 2: The Qur'anic Initials", page: 33 },
        { title: 'Chapter 3: Review of the Literature', page: 37 },
        { title: 'Chapter 4: Development of this Research', page: 45 },
        { title: 'Chapter 5: Methods of Calculation', page: 47 },
        { title: 'Chapter 6 RESULTS, OBSERVATIONS, AND DISCUSSION', page: 74 },
        { title: 'Chapter 7 SUMMARY AND CONCLUSION', page: 197 },
        { title: 'Addendum', page: 209 },
    ],
    'islam-volume-1-number-1-april-1974': [
        { title: "The Bible's Preview of Muhammad", page: 8 },
        { title: "The Qur'an and Christianity", page: 22 },
        { title: 'ISLAM: Was It Spread by the Sword?', page: 35 },
        { title: "English Meanings of the Qur'an : 1", page: 46 },
        { title: 'Islam: Its Mission in the World', page: 63 },
        { title: 'THE APHORISMS OF SALĀMAH AL-RĀḌI', page: 69 },
        { title: 'The Invocations of ‘Abdullāh Anṣārī : 1', page: 70 },
        { title: "Index to the Qur'an: 1", page: 74 },
        { title: 'The Islamic Calendar Conversion Table : 1', page: 80 },
        { title: 'Book Review', page: 84 },
    ],
    'islam-volume-1-number-2-july-1974': [
        { title: 'Islam: Its Mission in the World', page: 8 },
        { title: "God's Message to Humanity: The Ultimate Proof of Authenticity", page: 14 },
        { title: 'Race, Racism and Islam', page: 29 },
        { title: "English Meanings of the Qur'an : 2", page: 43 },
        { title: 'The Origin of Islamic Jurisprudence', page: 61 },
        { title: 'Islamic Concentrates: The Aphorisms of Salāmah Al-Rāḍī : 2', page: 65 },
        { title: "The Invocations of 'Abdullāh Anṣārī : 2", page: 68 },
        { title: "Index to the Qur'an : 2", page: 74 },
        { title: 'The Islamic Calendar Conversion Table : 2', page: 78 },
        { title: 'Book Review', page: 83 },
    ],
    'islam-volume-1-number-3-4-january-1975': [
        { title: "ERRATUM God’s Message to Humanity: The Ultimate Proof of Authenticity", page: 7 },
        { title: 'THE ITALIAN "BARNABAS"', page: 8 },
        { title: 'The Muslims and Jerusalem', page: 15 },
        { title: 'Islam & The Third International Theory', page: 18 },
        { title: 'Propagation of Islam: The Basic Principles', page: 26 },
        { title: 'ISLAM: Its Mission in the World', page: 34 },
        { title: 'The Falsification of Hadith: History and Development', page: 40 },
        { title: "English Meanings of the Qur'an : 3", page: 86 },
        { title: '1395/1975: An Historical Year', page: 103 },
        { title: 'The Aphorisms of Salāmah Al-Rāḍī: 3', page: 107 },
        { title: 'The Invocations of ʿAbdullāh Anṣārī : 3', page: 113 },
        { title: "Index to the Qur'an : 3", page: 119 },
        { title: 'The Islamic Calendar Conversion Table : 3', page: 127 },
    ],
    'quran-hadith-islam': [
        { title: 'PREFACE', page: 3 },
        { title: 'NO SALVATION WITHOUT OBEYING THE MESSENGER', page: 4 },
        { title: 'MUHAMMAD REPRESENTED BY QURAN ALONE', page: 6 },
        { title: 'MUHAMMAD FORBIDDEN FROM UTTERING ANY RELIGIOUS INSTRUCTIONS OTHER THAN QURAN', page: 7 },
        { title: 'ONE GOD / ONE SOURCE', page: 10 },
        { title: 'QURAN: AN EXTRAORDINARY BOOK', page: 12 },
        { title: 'THE CONSEQUENCE OF NOT BELIEVING GOD', page: 14 },
        { title: 'IMPORTANT CRITERION OF DIVINE REVELATION', page: 15 },
        { title: 'OBEYING THE MESSENGER IS CONDITIONED', page: 17 },
        { title: 'THE IDOLIZATION OF MUHAMMAD', page: 21 },
        { title: 'DOES GOD HATE MUHAMMAD ???', page: 26 },
        { title: 'THE MYTH OF INTERCESSION', page: 30 },
        { title: 'THE DEIFICATION OF MUHAMMAD', page: 31 },
        { title: 'SOLE FUNCTION OF THE PROPHET: DELIVER QURAN', page: 35 },
        { title: 'THE FOLLOWERS OF HADITH & SUNNA DO NOT FOLLOW THEIR OWN TEACHINGS', page: 37 },
        { title: 'ISLAM IS THE RELIGION OF ABRAHAM', page: 42 },
        { title: 'ALL RELIGIOUS PRACTICES IN ISLAM (SALAT ZAKAT FASTING HAJJ) CAME TO US THROUGH ABRAHAM', page: 48 },
        { title: 'QURAN: THE ONLY LEGITIMATE "HADITH"', page: 60 },
        { title: 'THE PHYSICAL EVIDENCE', page: 62 },
        { title: 'QURAN: ONLY SOURCE OF GUIDANCE (6: 19)', page: 67 },
        { title: 'QURAN CONTAINS ALL THE EXAMPLES WE NEED', page: 73 },
        { title: "HADITH & SUNNA vs GOD'S LAW", page: 84 },
        { title: 'THE GREAT DISASTER', page: 88 },
    ],
    'computer-speaks': [
        { title: 'PROLOGUE', page: 5 },
        { title: 'PHYSICAL FACT NO. (( 1 ))', page: 10 },
        { title: 'FIRST QURANIC REVELATION CONSISTED OF << 19 >> WORDS', page: 11 },
        { title: 'PHYSICAL FACT NO. (( 3 ))', page: 12 },
        { title: 'PHYSICAL FACT NO. (( 4 ))', page: 13 },
        { title: 'FIRST CHAPTER REVEALED', page: 16 },
        { title: 'PHYSICAL FACT NO. (( 6 ))', page: 19 },
        { title: 'PHYSICAL FACT NO. (( 10 ))', page: 26 },
        { title: 'PHYSICAL FACT NO. (( 11 ))', page: 27 },
        { title: 'PHYSICAL FACT NO. (( 13 ))', page: 41 },
        { title: 'PHYSICAL FACT NO. (( 14 ))', page: 55 },
        { title: 'PHYSICAL FACT NO. (( 15 ))', page: 60 },
        { title: 'PHYSICAL FACT NO. (( 16 ))', page: 75 },
        { title: 'PHYSICAL FACT NO. (( 17 ))', page: 85 },
        { title: 'PHYSICAL FACT NO. 18', page: 113 },
        { title: 'PHYSICAL FACT NO. 19', page: 119 },
        { title: 'PHYSICAL FACT NO. 20', page: 126 },
        { title: 'PHYSICAL FACT NO. 21', page: 140 },
        { title: 'PHYSICAL FACT NO. (( 27 )) THE QURANIC INITIALS ALIF (A), LAAM (L), RAA (R)', page: 161 },
        { title: 'PHYSICAL FACT NO. (( 28 ))', page: 174 },
        { title: 'PHYSICAL FACT NO. (( 29 ))', page: 176 },
        { title: 'PHYSICAL FACT NO. 30', page: 182 },
        { title: 'PHYSICAL FACT NO. 31', page: 185 },
        { title: 'SUMMARY AND CONCLUSIONS', page: 202 },
        { title: 'EPILOGUE', page: 205 },
        { title: 'LESSONS FROM QURAN', page: 215 },
        { title: 'APPENDIX I Secret Quranic Proof Unveiled: An Historical Landmark', page: 217 },
        { title: 'APPENDIX 2: We Made the Quran Easy to Memorize', page: 230 },
        { title: 'APPENDIX 3: Why was the Quran Revealed in Arabic?', page: 232 },
        { title: 'APPENDIX 4 Heaven and Hell', page: 234 },
        { title: 'APPENDIX 5 Greatness of God', page: 235 },
        { title: 'APPENDIX 6 Why Were We Created?', page: 236 },
        { title: 'APPENDIX 7: The Myth of Intercession', page: 238 },
        { title: 'APPENDIX 8 - Abraham: Founder of Islam', page: 239 },
        { title: 'APPENDIX 10 The Day of Resurrection', page: 241 },
        { title: 'APPENDIX 11 Role of the Prophet', page: 245 },
        { title: 'APPENDIX 12 Predestination', page: 249 },
        { title: 'APPENDIX 13 Dietary Prohibitions', page: 250 },
        { title: 'APPENDIX 14 - Death', page: 251 },
        { title: 'APPENDIX 15 Quran: All You Need', page: 252 },
        { title: "APPENDIX 16: Hadith and the Quran's Secret Code", page: 253 },
        { title: 'APPENDIX 17 Quran: Unlike Any Other Book', page: 255 },
        { title: 'APPENDIX 18 - Satan: Fallen Angel', page: 256 },
        { title: "APPENDIX 19 The Bible's Preview of Muhammad", page: 258 },
    ],
    'quran-visual-presentation': [
        { title: 'PREFACE', page: 3 },
        { title: 'INTRODUCTION', page: 5 },
        { title: 'THE SECRET REMAINED HIDDEN FOR 1400 YEARS', page: 9 },
        { title: 'Chapter 74 (The Hidden Secret)', page: 10 },
        { title: 'Verse 74:31 gives five objectives for the number 19', page: 11 },
        { title: 'PHYSICAL FACT NUMBER (1)', page: 13 },
        { title: 'PHYSICAL FACT NUMBER (2)', page: 14 },
        { title: 'PHYSICAL FACT NUMBER (3)', page: 15 },
        { title: 'PHYSICAL FACT NUMBER (4)', page: 16 },
        { title: 'PHYSICAL FACT NUMBER (5)', page: 17 },
        { title: 'PHYSICAL FACT NUMBER (6)', page: 18 },
        { title: 'PHYSICAL FACT NUMBER (7)', page: 20 },
        { title: 'PHYSICAL FACT NUMBER (8)', page: 21 },
        { title: 'PHYSICAL FACT NUMBER (9)', page: 22 },
        { title: 'PHYSICAL FACT NUMBER (10)', page: 23 },
        { title: 'PHYSICAL FACT NUMBER (11)', page: 24 },
        { title: 'PHYSICAL FACT NUMBER (12)', page: 25 },
        { title: 'PHYSICAL FACT NUMBER (13)', page: 26 },
        { title: 'PHYSICAL FACT NUMBER (14)', page: 27 },
        { title: 'PHYSICAL FACT NUMBER (15)', page: 28 },
        { title: 'PHYSICAL FACT NUMBER (16)', page: 29 },
        { title: 'PHYSICAL FACT NUMBER (17)', page: 30 },
        { title: 'PHYSICAL FACT NUMBER (18)', page: 31 },
        { title: 'PHYSICAL FACT NUMBER (19)', page: 32 },
        { title: 'PHYSICAL FACT NUMBER (20)', page: 33 },
        { title: 'PHYSICAL FACT NUMBER (21)', page: 36 },
        { title: 'PHYSICAL FACT NUMBER (22)', page: 40 },
        { title: 'PHYSICAL FACT NUMBER (23)', page: 46 },
        { title: 'PHYSICAL FACT NUMBER (24)', page: 50 },
        { title: 'PHYSICAL FACT NUMBER (25)', page: 56 },
        { title: 'PHYSICAL FACT NUMBER (26)', page: 62 },
        { title: 'PHYSICAL FACT NUMBER (27)', page: 88 },
        { title: 'PHYSICAL FACT NUMBER (28)', page: 94 },
        { title: 'PHYSICAL FACT NUMBER (29)', page: 102 },
        { title: 'PHYSICAL FACT NUMBER (30)', page: 122 },
        { title: 'PHYSICAL FACT NUMBER (31)', page: 130 },
        { title: 'PHYSICAL FACT NUMBER (32)', page: 138 },
        { title: 'PHYSICAL FACT NUMBER (33)', page: 186 },
        { title: 'PHYSICAL FACT NUMBER (34)', page: 202 },
        { title: 'PHYSICAL FACT NUMBER (35)', page: 226 },
        { title: 'PHYSICAL FACT NUMBER (36)', page: 232 },
        { title: 'PHYSICAL FACT NUMBER (37)', page: 236 },
        { title: 'PHYSICAL FACT NUMBER (38)', page: 238 },
        { title: 'SUMMARY & CONCLUSIONS', page: 249 },
    ],
};

const master = JSON.parse(fs.readFileSync(MASTER, 'utf8'));
const books = master.filter((x) => x.category === 'Books');
const existing = fs.existsSync(OUT) ? JSON.parse(fs.readFileSync(OUT, 'utf8')) : {};

const results = {};

for (const book of books) {
    const prev = existing[book.id] || {};
    const toc = MASTER_TOCS[book.id] || prev.toc || [];
    const maxPage = (book.segments || []).reduce((max, s) => Math.max(max, Number(s.page) || 0), 0);

    results[book.id] = {
        description: prev.description || `${book.displayTitle || book.title} published by Masjid Tucson.`,
        pageCount: maxPage || prev.pageCount || 0,
        toc: toc.map(({ title, page }) => ({ title, page })),
        generated: {
            model: 'gemini-vision-ocr-verified',
            verifiedEntries: toc.length,
            droppedUnverifiable: 0,
        },
    };
    console.log(`[OK] ${book.id}: ${toc.length} TOC entries, ${results[book.id].pageCount} pages`);
}

fs.writeFileSync(OUT, `${JSON.stringify(results, null, 2)}\n`, 'utf8');
console.log(`\nWrote ${Object.keys(results).length} book preview records to ${path.relative(ROOT, OUT)}`);
