
-- 1. Media Table (Stores metadata for videos/audios)
create table public.media (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  slug text not null unique, -- e.g. "sermon-1987-06-05"
  type text not null check (type in ('sermon', 'quran-study', 'audio', 'video-program')),
  date_recorded date,
  duration_seconds integer,
  youtube_id text,
  local_filename text, -- to match with your local files
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Transcripts Table (Searchable text segments)
-- note: We could store the whole JSON, but storing segments enables Postgres Full Text Search (FTS)
create table public.transcript_segments (
  id bigint generated by default as identity primary key,
  media_id uuid references public.media(id) on delete cascade not null,
  segment_index integer not null, -- 0, 1, 2...
  start_time float not null,
  end_time float not null,
  speaker text,
  content text not null,
  search_vector tsvector generated always as (to_tsvector('english', content)) stored
);

-- Index for fast text search
create index idx_transcript_search on public.transcript_segments using GIN(search_vector);
create index idx_transcript_media on public.transcript_segments(media_id);

-- 3. User Progress (Tracks where users left off)
create table public.user_progress (
  user_id uuid references auth.users(id) on delete cascade not null,
  media_id uuid references public.media(id) on delete cascade not null,
  current_timestamp float not null default 0,
  is_completed boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, media_id)
);

-- 4. Enable Row Level Security (RLS)
alter table public.media enable row level security;
alter table public.transcript_segments enable row level security;
alter table public.user_progress enable row level security;

-- 5. Policies (Permissions)
-- Everyone can read media and transcripts
create policy "Public Media Access" on public.media for select using (true);
create policy "Public Transcript Access" on public.transcript_segments for select using (true);

-- Users can only see/edit their OWN progress
create policy "User View Own Progress" on public.user_progress for select using (auth.uid() = user_id);
create policy "User Update Own Progress" on public.user_progress for insert with check (auth.uid() = user_id);
create policy "User Modify Own Progress" on public.user_progress for update using (auth.uid() = user_id);
