CHAPTER_METADATA = {
    1: {'revelation_order': 5, 'total_verses': 7, 'name_arabic': 'الفاتحة', 'name_english': 'The Key'},
    2: {'revelation_order': 87, 'total_verses': 286, 'name_arabic': 'البقرة', 'name_english': 'The Heifer'},
    3: {'revelation_order': 89, 'total_verses': 200, 'name_arabic': 'آل عمران', 'name_english': 'The Amramites'},
    4: {'revelation_order': 92, 'total_verses': 176, 'name_arabic': 'النساء', 'name_english': 'The Women'},
    5: {'revelation_order': 112, 'total_verses': 120, 'name_arabic': 'المائدة', 'name_english': 'The Feast'},
    6: {'revelation_order': 55, 'total_verses': 165, 'name_arabic': 'الأنعام', 'name_english': 'The Livestock'},
    7: {'revelation_order': 39, 'total_verses': 206, 'name_arabic': 'الأعراف', 'name_english': 'The Purgatory'},
    8: {'revelation_order': 88, 'total_verses': 75, 'name_arabic': 'الأنفال', 'name_english': 'The Spoils of War'},
    9: {'revelation_order': 113, 'total_verses': 127, 'name_arabic': 'براءة', 'name_english': 'Ultimatum'},
    10: {'revelation_order': 51, 'total_verses': 109, 'name_arabic': 'يونس', 'name_english': 'Jonah'},
    11: {'revelation_order': 52, 'total_verses': 123, 'name_arabic': 'هود', 'name_english': 'Hood'},
    12: {'revelation_order': 53, 'total_verses': 111, 'name_arabic': 'يوسف', 'name_english': 'Joseph'},
    13: {'revelation_order': 96, 'total_verses': 43, 'name_arabic': 'الرعد', 'name_english': 'The Thunder'},
    14: {'revelation_order': 72, 'total_verses': 52, 'name_arabic': 'إبراهيم', 'name_english': 'Abraham'},
    15: {'revelation_order': 54, 'total_verses': 99, 'name_arabic': 'الحجر', 'name_english': 'The Hijr Valley'},
    16: {'revelation_order': 70, 'total_verses': 128, 'name_arabic': 'النّحل', 'name_english': 'The Bee'},
    17: {'revelation_order': 50, 'total_verses': 111, 'name_arabic': 'بني إسرءيل', 'name_english': 'The Children of Israel'},
    18: {'revelation_order': 69, 'total_verses': 110, 'name_arabic': 'الكهف', 'name_english': 'The Cave'},
    19: {'revelation_order': 44, 'total_verses': 98, 'name_arabic': 'مريم', 'name_english': 'Mary'},
    20: {'revelation_order': 45, 'total_verses': 135, 'name_arabic': 'طه', 'name_english': 'T-H'},
    21: {'revelation_order': 73, 'total_verses': 112, 'name_arabic': 'الأنبياء', 'name_english': 'The Prophets'},
    22: {'revelation_order': 103, 'total_verses': 78, 'name_arabic': 'الحج', 'name_english': 'The Pilgrimage'},
    23: {'revelation_order': 74, 'total_verses': 118, 'name_arabic': 'المؤمنون', 'name_english': 'The Believers'},
    24: {'revelation_order': 102, 'total_verses': 64, 'name_arabic': 'النّور', 'name_english': 'The Light'},
    25: {'revelation_order': 42, 'total_verses': 77, 'name_arabic': 'الفرقان', 'name_english': 'The Statute Book'},
    26: {'revelation_order': 47, 'total_verses': 227, 'name_arabic': 'الشعراء', 'name_english': 'The Poets'},
    27: {'revelation_order': 48, 'total_verses': 93, 'name_arabic': 'النّمل', 'name_english': 'The Ant'},
    28: {'revelation_order': 49, 'total_verses': 88, 'name_arabic': 'القصص', 'name_english': 'The History'},
    29: {'revelation_order': 85, 'total_verses': 69, 'name_arabic': 'العنكبوت', 'name_english': 'The Spider'},
    30: {'revelation_order': 84, 'total_verses': 60, 'name_arabic': 'الروم', 'name_english': 'The Romans'},
    31: {'revelation_order': 57, 'total_verses': 34, 'name_arabic': 'لقمان', 'name_english': 'Luqmaan'},
    32: {'revelation_order': 75, 'total_verses': 30, 'name_arabic': 'السجدة', 'name_english': 'Prostration'},
    33: {'revelation_order': 90, 'total_verses': 73, 'name_arabic': 'الأحزاب', 'name_english': 'The Parties'},
    34: {'revelation_order': 58, 'total_verses': 54, 'name_arabic': 'سبإ', 'name_english': 'Sheba'},
    35: {'revelation_order': 43, 'total_verses': 45, 'name_arabic': 'فاطر', 'name_english': 'Initiator'},
    36: {'revelation_order': 41, 'total_verses': 83, 'name_arabic': 'يس', 'name_english': 'Y-S'},
    37: {'revelation_order': 56, 'total_verses': 182, 'name_arabic': 'الصّافات', 'name_english': 'The Arrangers'},
    38: {'revelation_order': 38, 'total_verses': 88, 'name_arabic': 'ص', 'name_english': 'S'},
    39: {'revelation_order': 59, 'total_verses': 75, 'name_arabic': 'الزُّمر', 'name_english': 'The Throngs'},
    40: {'revelation_order': 60, 'total_verses': 85, 'name_arabic': 'غافر', 'name_english': 'Forgiver'},
    41: {'revelation_order': 61, 'total_verses': 54, 'name_arabic': 'فصلت', 'name_english': 'Detailed'},
    42: {'revelation_order': 62, 'total_verses': 53, 'name_arabic': 'الشورى', 'name_english': 'Consultation'},
    43: {'revelation_order': 63, 'total_verses': 89, 'name_arabic': 'الزخرف', 'name_english': 'The Ornaments'},
    44: {'revelation_order': 64, 'total_verses': 59, 'name_arabic': 'الدّخان', 'name_english': 'The Smoke'},
    45: {'revelation_order': 65, 'total_verses': 37, 'name_arabic': 'الجاثية', 'name_english': 'The Kneeling'},
    46: {'revelation_order': 66, 'total_verses': 35, 'name_arabic': 'الأحقاف', 'name_english': 'The Dunes'},
    47: {'revelation_order': 95, 'total_verses': 38, 'name_arabic': 'محمد', 'name_english': 'Muhammed'},
    48: {'revelation_order': 111, 'total_verses': 29, 'name_arabic': 'الفتح', 'name_english': 'Victory'},
    49: {'revelation_order': 106, 'total_verses': 18, 'name_arabic': 'الحجرات', 'name_english': 'The Walls'},
    50: {'revelation_order': 34, 'total_verses': 45, 'name_arabic': 'ق', 'name_english': 'Q'},
    51: {'revelation_order': 67, 'total_verses': 60, 'name_arabic': 'الذاريات', 'name_english': 'Driver of the Winds'},
    52: {'revelation_order': 76, 'total_verses': 49, 'name_arabic': 'الطور', 'name_english': 'Mount Sinai'},
    53: {'revelation_order': 23, 'total_verses': 62, 'name_arabic': 'النّجم', 'name_english': 'The Stars'},
    54: {'revelation_order': 37, 'total_verses': 55, 'name_arabic': 'القمر', 'name_english': 'The Moon'},
    55: {'revelation_order': 97, 'total_verses': 78, 'name_arabic': 'الرحمن', 'name_english': 'The Gracious'},
    56: {'revelation_order': 46, 'total_verses': 96, 'name_arabic': 'الواقعة', 'name_english': 'The Inevitable'},
    57: {'revelation_order': 94, 'total_verses': 29, 'name_arabic': 'الحديد', 'name_english': 'Iron'},
    58: {'revelation_order': 105, 'total_verses': 22, 'name_arabic': 'المجادلة', 'name_english': 'The Debate'},
    59: {'revelation_order': 101, 'total_verses': 24, 'name_arabic': 'الحشر', 'name_english': 'The Exodus'},
    60: {'revelation_order': 91, 'total_verses': 13, 'name_arabic': 'الممتحنة', 'name_english': 'The Test'},
    61: {'revelation_order': 109, 'total_verses': 14, 'name_arabic': 'الصف', 'name_english': 'The Column'},
    62: {'revelation_order': 110, 'total_verses': 11, 'name_arabic': 'الجمعة', 'name_english': 'Friday'},
    63: {'revelation_order': 104, 'total_verses': 11, 'name_arabic': 'المنافقون', 'name_english': 'The Hypocrites'},
    64: {'revelation_order': 108, 'total_verses': 18, 'name_arabic': 'التغابن', 'name_english': 'Mutual Blaming'},
    65: {'revelation_order': 99, 'total_verses': 12, 'name_arabic': 'الطلاق', 'name_english': 'Divorce'},
    66: {'revelation_order': 107, 'total_verses': 12, 'name_arabic': 'التحريم', 'name_english': 'Prohibition'},
    67: {'revelation_order': 77, 'total_verses': 30, 'name_arabic': 'الملك', 'name_english': 'Kingship'},
    68: {'revelation_order': 2, 'total_verses': 52, 'name_arabic': 'القلم', 'name_english': 'The Pen'},
    69: {'revelation_order': 78, 'total_verses': 52, 'name_arabic': 'الحاقة', 'name_english': 'Incontestable'},
    70: {'revelation_order': 79, 'total_verses': 44, 'name_arabic': 'المعارج', 'name_english': 'The Heights'},
    71: {'revelation_order': 71, 'total_verses': 28, 'name_arabic': 'نوح', 'name_english': 'Noah'},
    72: {'revelation_order': 40, 'total_verses': 28, 'name_arabic': 'الجن', 'name_english': 'Jinns'},
    73: {'revelation_order': 3, 'total_verses': 20, 'name_arabic': 'المزمل', 'name_english': 'Cloaked'},
    74: {'revelation_order': 4, 'total_verses': 56, 'name_arabic': 'المدثر', 'name_english': 'The Hidden Secret'},
    75: {'revelation_order': 31, 'total_verses': 40, 'name_arabic': 'القيامة', 'name_english': 'Resurrection'},
    76: {'revelation_order': 98, 'total_verses': 31, 'name_arabic': 'الانسان', 'name_english': 'The Human'},
    77: {'revelation_order': 33, 'total_verses': 50, 'name_arabic': 'المرسلات', 'name_english': 'Dispatched'},
    78: {'revelation_order': 80, 'total_verses': 40, 'name_arabic': 'النبأ', 'name_english': 'The Event'},
    79: {'revelation_order': 81, 'total_verses': 46, 'name_arabic': 'النازعات', 'name_english': 'The Snatchers'},
    80: {'revelation_order': 24, 'total_verses': 42, 'name_arabic': 'عبس', 'name_english': 'He Frowned'},
    81: {'revelation_order': 7, 'total_verses': 29, 'name_arabic': 'التكوير', 'name_english': 'The Rolling'},
    82: {'revelation_order': 82, 'total_verses': 19, 'name_arabic': 'الانفطار', 'name_english': 'The Shattering'},
    83: {'revelation_order': 86, 'total_verses': 36, 'name_arabic': 'المطففين', 'name_english': 'The Cheaters'},
    84: {'revelation_order': 83, 'total_verses': 25, 'name_arabic': 'الانشقاق', 'name_english': 'The Rupture'},
    85: {'revelation_order': 27, 'total_verses': 22, 'name_arabic': 'البروج', 'name_english': 'The Galaxies'},
    86: {'revelation_order': 36, 'total_verses': 17, 'name_arabic': 'الطارق', 'name_english': 'The Bright Star'},
    87: {'revelation_order': 8, 'total_verses': 19, 'name_arabic': 'الأعلى', 'name_english': 'The Most High'},
    88: {'revelation_order': 68, 'total_verses': 26, 'name_arabic': 'الغاشية', 'name_english': 'Overwhelming'},
    89: {'revelation_order': 10, 'total_verses': 30, 'name_arabic': 'الفجر', 'name_english': 'Dawn'},
    90: {'revelation_order': 35, 'total_verses': 20, 'name_arabic': 'البلد', 'name_english': 'The Town'},
    91: {'revelation_order': 26, 'total_verses': 15, 'name_arabic': 'الشمس', 'name_english': 'The Sun'},
    92: {'revelation_order': 9, 'total_verses': 21, 'name_arabic': 'الليل', 'name_english': 'The Night'},
    93: {'revelation_order': 11, 'total_verses': 11, 'name_arabic': 'الضحى', 'name_english': 'The Forenoon'},
    94: {'revelation_order': 12, 'total_verses': 8, 'name_arabic': 'الشرح', 'name_english': 'Cooling the Temper'},
    95: {'revelation_order': 28, 'total_verses': 8, 'name_arabic': 'التين', 'name_english': 'The Fig'},
    96: {'revelation_order': 1, 'total_verses': 19, 'name_arabic': 'العلق', 'name_english': 'The Embryo'},
    97: {'revelation_order': 25, 'total_verses': 5, 'name_arabic': 'القدر', 'name_english': 'The Destiny'},
    98: {'revelation_order': 100, 'total_verses': 8, 'name_arabic': 'البينة', 'name_english': 'The Proof'},
    99: {'revelation_order': 93, 'total_verses': 8, 'name_arabic': 'الزلزلة', 'name_english': 'The Quake'},
    100: {'revelation_order': 14, 'total_verses': 11, 'name_arabic': 'العاديات', 'name_english': 'The Gallopers'},
    101: {'revelation_order': 30, 'total_verses': 11, 'name_arabic': 'القارعة', 'name_english': 'The Shocker'},
    102: {'revelation_order': 16, 'total_verses': 8, 'name_arabic': 'التكاثر', 'name_english': 'Hoarding'},
    103: {'revelation_order': 13, 'total_verses': 3, 'name_arabic': 'العصر', 'name_english': 'The Afternoon'},
    104: {'revelation_order': 32, 'total_verses': 9, 'name_arabic': 'الهمزة', 'name_english': 'The Backbiter'},
    105: {'revelation_order': 19, 'total_verses': 5, 'name_arabic': 'الفيل', 'name_english': 'The Elephant'},
    106: {'revelation_order': 29, 'total_verses': 4, 'name_arabic': 'قريش', 'name_english': 'Quraish Tribe'},
    107: {'revelation_order': 17, 'total_verses': 7, 'name_arabic': 'الماعون', 'name_english': 'Charity'},
    108: {'revelation_order': 15, 'total_verses': 3, 'name_arabic': 'الكوثر', 'name_english': 'Bounty'},
    109: {'revelation_order': 18, 'total_verses': 6, 'name_arabic': 'الكافرون', 'name_english': 'The Disbelievers'},
    110: {'revelation_order': 114, 'total_verses': 3, 'name_arabic': 'النّصر', 'name_english': 'Triumph'},
    111: {'revelation_order': 6, 'total_verses': 5, 'name_arabic': 'المسد', 'name_english': 'Thorns'},
    112: {'revelation_order': 22, 'total_verses': 4, 'name_arabic': 'الإخلاص', 'name_english': 'Absoluteness'},
    113: {'revelation_order': 20, 'total_verses': 5, 'name_arabic': 'الفلق', 'name_english': 'Daybreak'},
    114: {'revelation_order': 21, 'total_verses': 6, 'name_arabic': 'الناس', 'name_english': 'People'},
}
