import {
  FileText,
  Folder,
  FolderOpen,
  Tag,
  MagnifyingGlass,
  Trash,
  Gear,
  Plus,
  X,
  CaretRight,
  CaretDown,
  CaretLeft,
  CaretUp,
  Lock,
  LockOpen,
  ArrowsOut,
  ArrowsIn,
  BookOpen,
  Sparkle,
  Quotes,
  Warning,
  Info,
  DotsThreeVertical,
  DotsSixVertical,
  Copy,
  SquareSplitHorizontal,
  SquareSplitVertical,
  FilePdf,
  FileAudio,
  FileVideo,
  FileImage,
  Table,
  BracketsCurly,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Eye,
  EyeSlash,
  ClockCounterClockwise,
  Pencil,
  Check,
  Sun,
  Moon,
  Desktop,
  Globe,
  Bookmark,
  PushPin,
  List,
  ListBullets,
  ListNumbers,
  TextH,
  Code,
  TextB,
  TextItalic,
  Columns,
  FileCode,
  User,
  Calendar,
  Hash,
  SlidersHorizontal,
  ShareNetwork,
  DownloadSimple,
  UploadSimple,
  FilePlus,
  FolderPlus,
  ArrowClockwise,
  Printer,
  FileHtml,
  ShieldCheck,
  WarningCircle,
  IconProps
} from '@phosphor-icons/react'

export type IconWeight = 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone'

export const IconMap = {
  file: FileText,
  folder: Folder,
  folderOpen: FolderOpen,
  tag: Tag,
  search: MagnifyingGlass,
  trash: Trash,
  settings: Gear,
  graph: ShareNetwork,
  plus: Plus,
  close: X,
  chevronRight: CaretRight,
  chevronDown: CaretDown,
  chevronLeft: CaretLeft,
  chevronUp: CaretUp,
  lock: Lock,
  unlock: LockOpen,
  maximize: ArrowsOut,
  minimize: ArrowsIn,
  book: BookOpen,
  sparkle: Sparkle,
  quotes: Quotes,
  warning: Warning,
  info: Info,
  moreVertical: DotsThreeVertical,
  dragHandle: DotsSixVertical,
  copy: Copy,
  splitHorizontal: SquareSplitHorizontal,
  splitVertical: SquareSplitVertical,
  filePdf: FilePdf,
  fileAudio: FileAudio,
  fileVideo: FileVideo,
  fileImage: FileImage,
  table: Table,
  brackets: BracketsCurly,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  eye: Eye,
  eyeSlash: EyeSlash,
  history: ClockCounterClockwise,
  pencil: Pencil,
  check: Check,
  sun: Sun,
  moon: Moon,
  desktop: Desktop,
  globe: Globe,
  bookmark: Bookmark,
  pin: PushPin,
  list: List,
  listBullets: ListBullets,
  listNumbers: ListNumbers,
  heading: TextH,
  code: Code,
  bold: TextB,
  italic: TextItalic,
  columns: Columns,
  fileCode: FileCode,
  user: User,
  calendar: Calendar,
  hash: Hash,
  sliders: SlidersHorizontal,
  download: DownloadSimple,
  upload: UploadSimple,
  filePlus: FilePlus,
  folderPlus: FolderPlus,
  refresh: ArrowClockwise,
  print: Printer,
  fileHtml: FileHtml,
  shieldCheck: ShieldCheck,
  warningCircle: WarningCircle
} as const

export interface AppIconProps extends Omit<IconProps, 'weight'> {
  name: keyof typeof IconMap
  weight?: IconWeight
  className?: string
  size?: number | string
}

export function AppIcon({ name, weight = 'regular', size = 16, className = '', ...props }: AppIconProps) {
  const IconComponent = IconMap[name] || FileText
  return <IconComponent weight={weight} size={size} className={className} {...props} />
}
