/** Accessor for the Studio media index generated by
 * `npm run generate:studio-media` (scripts/generate/build_studio_media_index.mjs).
 *
 * The index lives in `studio/public/media/` rather than being bundled: the
 * catalog is ~0.9 MB and the 151 transcripts total ~7.5 MB, so both are fetched
 * over the app's own origin (Vite dev server or the Tauri asset protocol) and
 * cached in memory. Transcripts are only pulled when a lecture is opened. */

export type MediaType = 'video-program' | 'quran-study' | 'messenger-audio'

export interface MediaChapter {
  id: number
  startTime: number
  endTime?: number
  title: string
  speaker?: string
}

export interface TranscriptCue {
  id: number
  startTime: number
  endTime: number
  text: string
  speaker?: string
}

export interface MediaItem {
  id: string
  /** Filename-safe form of `id`, used to address the transcript sidecar. */
  slug: string
  title: string
  displayTitle: string
  type: MediaType
  author: string
  date?: string
  year?: number
  duration?: string
  durationSeconds?: number
  youtubeId?: string
  youtubeUrl?: string
  thumbnail?: string
  /** Direct MP4/MP3, or a `tauri://`-converted local file the user attached. */
  streamUrl?: string
  description?: string
  primaryNumber?: number
  cueCount?: number
  speakers?: string[]
  chapters: MediaChapter[]
  cues?: TranscriptCue[]
}

export interface MediaTranscript {
  id: string
  slug: string
  durationSeconds?: number
  cues: TranscriptCue[]
  cuesAr?: TranscriptCue[]
}

/** Columnar cue tuple: [start, end, text, speakerIndex] (-1 means unattributed). */
type RawCue = [number, number, string, number]

interface RawTranscript {
  id: string
  slug: string
  durationSeconds?: number
  speakers?: string[]
  cues?: RawCue[]
  speakersAr?: string[]
  cuesAr?: RawCue[]
}

interface RawCatalog {
  count: number
  items: MediaItem[]
}

export const MEDIA_TYPE_LABEL: Record<MediaType, string> = {
  'video-program': 'Video Program',
  'quran-study': 'Quran Study',
  'messenger-audio': 'Messenger Audio',
}

const CATALOG_URL = 'media/catalog.json'
const TRANSCRIPT_URL = (slug: string) => `media/transcripts/${slug}.json`

let catalogPromise: Promise<MediaItem[]> | null = null
const transcriptCache = new Map<string, Promise<MediaTranscript>>()

/** Resolves an app-relative asset path against the document base so the same
 * code works under the Vite dev server and the Tauri asset protocol. */
function assetUrl(relative: string): string {
  if (typeof document === 'undefined') return `/${relative}`
  const base = document.baseURI || `${location.origin}/`
  return new URL(relative, base).toString()
}

export function loadMediaCatalog(): Promise<MediaItem[]> {
  if (!catalogPromise) {
    catalogPromise = fetch(assetUrl(CATALOG_URL))
      .then((response) => {
        if (!response.ok) throw new Error(`catalog ${response.status}`)
        return response.json() as Promise<RawCatalog>
      })
      .then((parsed) => (Array.isArray(parsed?.items) ? parsed.items : []))
      .catch((error) => {
        // A missing index must not take the panel down with it: the empty
        // catalog renders as an actionable "run the generator" empty state.
        console.error('[mediaCatalog] failed to load media catalog', error)
        catalogPromise = null
        return []
      })
  }
  return catalogPromise
}

function decodeCues(cues: RawCue[] | undefined, speakers: string[] | undefined): TranscriptCue[] {
  if (!cues) return []
  return cues.map(([startTime, endTime, text, speakerIndex], index) => ({
    id: index,
    startTime,
    endTime,
    text,
    speaker: speakerIndex >= 0 ? speakers?.[speakerIndex] : undefined,
  }))
}

export function loadTranscript(slug: string): Promise<MediaTranscript> {
  const cached = transcriptCache.get(slug)
  if (cached) return cached

  const pending = fetch(assetUrl(TRANSCRIPT_URL(slug)))
    .then((response) => {
      if (!response.ok) throw new Error(`transcript ${response.status}`)
      return response.json() as Promise<RawTranscript>
    })
    .then((raw) => {
      const cuesAr = decodeCues(raw.cuesAr, raw.speakersAr)
      return {
        id: raw.id,
        slug: raw.slug,
        durationSeconds: raw.durationSeconds,
        cues: decodeCues(raw.cues, raw.speakers),
        ...(cuesAr.length ? { cuesAr } : {}),
      }
    })
    .catch((error) => {
      console.error(`[mediaCatalog] failed to load transcript ${slug}`, error)
      transcriptCache.delete(slug)
      return { id: slug, slug, cues: [] }
    })

  transcriptCache.set(slug, pending)
  return pending
}

/* ------------------------------------------------------------------ *
 * Time formatting — pure helpers, unit-tested from the root workspace *
 * ------------------------------------------------------------------ */

/** `99` -> `01:39`, `3723` -> `1:02:03`. Hours only appear when non-zero, which
 * is what a citation reads best as. */
export function formatSeconds(seconds: number): string {
  const safe = Number.isFinite(seconds) && seconds > 0 ? Math.floor(seconds) : 0
  const hours = Math.floor(safe / 3600)
  const minutes = Math.floor((safe % 3600) / 60)
  const secs = safe % 60
  const pad = (value: number) => String(value).padStart(2, '0')
  return hours > 0 ? `${hours}:${pad(minutes)}:${pad(secs)}` : `${pad(minutes)}:${pad(secs)}`
}

/** Inverse of `formatSeconds`, tolerant of the forms that turn up in prose:
 * `01:39`, `1:02:03`, `99`, `1h2m3s`, `5m42s`. Returns null when unparseable. */
export function parseTimestamp(value: string | null | undefined): number | null {
  if (!value) return null
  const text = value.trim().toLowerCase()
  if (!text) return null

  if (/^\d+(?:\.\d+)?$/.test(text)) return Number(text)

  const parts = text.split(':')
  if (parts.length > 1 && parts.every((part) => /^\d+(?:\.\d+)?$/.test(part))) {
    return parts.reduce((total, part) => total * 60 + Number(part), 0)
  }

  const units = text.match(/^(?:(\d+(?:\.\d+)?)h)?(?:(\d+(?:\.\d+)?)m)?(?:(\d+(?:\.\d+)?)s)?$/)
  if (units && units.slice(1).some(Boolean)) {
    return Number(units[1] || 0) * 3600 + Number(units[2] || 0) * 60 + Number(units[3] || 0)
  }

  return null
}

/* ------------------------------------------- *
 * Reference parsing (search box / deep links) *
 * ------------------------------------------- */

export interface MediaReference {
  /** Catalog id when the reference resolved to one, otherwise null. */
  id: string | null
  /** Seek target in seconds, when the reference carried one. */
  timestamp?: number
  /** YouTube id, for a pasted YouTube URL that no catalog record claims. */
  youtubeId?: string
}

/**
 * Parses anything a researcher is likely to paste into the media selector:
 *
 *   sa://media/video-program/what-is-life-all-about?t=99
 *   https://submissionarchives.com/media/quran-study/01%20Quran...
 *   https://www.youtube.com/watch?v=tNqQJR5LyXo&t=99s
 *   https://youtu.be/tNqQJR5LyXo?t=99
 *   video-program/what-is-life-all-about
 *   QS-01 / QS01 / MA 72
 *
 * Catalog lookup is left to `resolveReference` so this stays pure.
 */
export function parseMediaReference(input: string): MediaReference | null {
  const text = (input ?? '').trim()
  if (!text) return null

  const timeFromQuery = (query: string | null): number | undefined => {
    const parsed = parseTimestamp(query?.replace(/s$/, ''))
    return parsed == null ? undefined : parsed
  }

  // sa://media/<id>?t=
  const saMatch = text.match(/^sa:\/\/media\/([^?#]+)(?:\?([^#]*))?/i)
  if (saMatch) {
    const params = new URLSearchParams(saMatch[2] ?? '')
    return { id: safeDecode(saMatch[1]), timestamp: timeFromQuery(params.get('t')) }
  }

  if (/^https?:\/\//i.test(text)) {
    let url: URL
    try {
      url = new URL(text)
    } catch {
      return null
    }
    const timestamp = timeFromQuery(url.searchParams.get('t') || url.searchParams.get('start'))

    if (/(^|\.)youtube\.com$/i.test(url.hostname)) {
      const videoId = url.searchParams.get('v') || url.pathname.replace(/^\/(embed|shorts|live)\//, '')
      return { id: null, youtubeId: videoId || undefined, timestamp }
    }
    if (/(^|\.)youtu\.be$/i.test(url.hostname)) {
      return { id: null, youtubeId: url.pathname.replace(/^\//, '') || undefined, timestamp }
    }

    const mediaPath = url.pathname.match(/\/media\/(.+)$/)
    if (mediaPath) return { id: safeDecode(mediaPath[1]), timestamp }
    return null
  }

  // Bare catalog id (contains the type prefix) or a short record code.
  if (text.includes('/')) return { id: safeDecode(text) }
  return { id: text }
}

function safeDecode(value: string): string {
  try {
    return decodeURIComponent(value)
  } catch {
    return value
  }
}

/** Short record codes: `QS-01`, `qs1`, `MA 72`. Returns the catalog type and
 * number so a reference can be matched against `primaryNumber`. */
export function parseRecordCode(input: string): { type: MediaType; number: number } | null {
  const match = (input ?? '').trim().match(/^(qs|ma)[\s-]*0*(\d{1,3})$/i)
  if (!match) return null
  return {
    type: match[1].toLowerCase() === 'qs' ? 'quran-study' : 'messenger-audio',
    number: Number(match[2]),
  }
}

/** Resolves a parsed reference against the catalog. Falls back through exact
 * id, record code, YouTube id, then slug, so partial references still land. */
export function resolveReference(items: MediaItem[], reference: MediaReference | null): MediaItem | null {
  if (!reference) return null

  if (reference.youtubeId) {
    const byYoutube = items.find((item) => item.youtubeId === reference.youtubeId)
    if (byYoutube) return byYoutube
  }

  const key = reference.id
  if (!key) return null

  const exact = items.find((item) => item.id === key)
  if (exact) return exact

  const code = parseRecordCode(key)
  if (code) {
    const byCode = items.find((item) => item.type === code.type && item.primaryNumber === code.number)
    if (byCode) return byCode
  }

  const lowered = key.toLowerCase()
  return (
    items.find((item) => item.slug === lowered) ??
    items.find((item) => item.id.toLowerCase() === lowered) ??
    items.find((item) => item.id.toLowerCase().endsWith(`/${lowered}`)) ??
    null
  )
}

/* ------------------- *
 * Playback-time lookup *
 * ------------------- */

/** Index of the cue covering `time`, or the last cue that started before it.
 * Binary search: transcripts run to 1,700 cues and this is called at 4 Hz. */
export function findActiveCueIndex(cues: TranscriptCue[], time: number): number {
  if (!cues.length) return -1
  let low = 0
  let high = cues.length - 1
  let found = -1
  while (low <= high) {
    const mid = (low + high) >> 1
    if (cues[mid].startTime <= time) {
      found = mid
      low = mid + 1
    } else {
      high = mid - 1
    }
  }
  if (found < 0) return -1
  const cue = cues[found]
  // A gap between cues should not keep the previous line highlighted forever.
  if (cue.endTime > cue.startTime && time >= cue.endTime + 1) return -1
  return found
}

export function findActiveChapterIndex(chapters: MediaChapter[], time: number): number {
  let found = -1
  for (let index = 0; index < chapters.length; index += 1) {
    if (chapters[index].startTime <= time) found = index
    else break
  }
  return found
}

/* -------------- *
 * Recents (local) *
 * -------------- */

const RECENTS_KEY = 'sa-studio-media-recents'
const RECENTS_LIMIT = 8

export function readRecentMediaIds(): string[] {
  try {
    const raw = localStorage.getItem(RECENTS_KEY)
    const parsed = raw ? JSON.parse(raw) : []
    return Array.isArray(parsed) ? parsed.filter((entry): entry is string => typeof entry === 'string') : []
  } catch {
    return []
  }
}

export function recordRecentMediaId(id: string): string[] {
  const next = [id, ...readRecentMediaIds().filter((entry) => entry !== id)].slice(0, RECENTS_LIMIT)
  try {
    localStorage.setItem(RECENTS_KEY, JSON.stringify(next))
  } catch {
    // A full or disabled localStorage costs the recents list, nothing more.
  }
  return next
}

/* ----------------------- *
 * Local stream attachments *
 * ----------------------- */

const STREAMS_KEY = 'sa-studio-media-streams'

/** Every catalog record plays from YouTube (see scripts/.../build_studio_media_index.mjs
 * warnings — none are missing a youtubeId), which means no playback offline. A
 * researcher can attach a local MP4/MP3 per record instead; the mapping is kept
 * out of the note so notes stay portable between machines. */
export function readLocalStreams(): Record<string, string> {
  try {
    const raw = localStorage.getItem(STREAMS_KEY)
    const parsed = raw ? JSON.parse(raw) : {}
    return parsed && typeof parsed === 'object' ? (parsed as Record<string, string>) : {}
  } catch {
    return {}
  }
}

export function writeLocalStream(id: string, filePath: string | null): Record<string, string> {
  const streams = readLocalStreams()
  if (filePath) streams[id] = filePath
  else delete streams[id]
  try {
    localStorage.setItem(STREAMS_KEY, JSON.stringify(streams))
  } catch {
    // Non-fatal: the attachment simply will not survive a restart.
  }
  return streams
}
