export const PLAYLIST_ORDER: Record<string, number> = {
    // Video Programs
    "What Life is All About & Who is GOD": 1,
    "Witness a Miracle & World News Bulletin": 2,
    "Mathematical Miracle of Quran": 3,
    "Essentials of Submission Islam": 4,
    "Principles of Contact Prayers Salat": 5,
    "Principles of Friday Prayer": 6,
    "Old Message, New Messenger": 7,
    "The Great Debate Dr. Rashad Khalifa vs Dr. Abdel Rahman": 8,
    "In Defence of the Bible": 9,
    "Evolution or Creation, The Final Argument by Dr Rashad Khalifa": 10,
    "King of Chaos": 11,
    "Explaining the Fulfillment of the Covenant": 34,
    "Final Speech by Dr. Rashad Khalifa (1989 Conference)": 45,
    "City Council Al-Fateha Recitation": 46,
    "Excerpts From a Radio Debate With dr Rashad Khalifa": 47,
    "World News Bulletin": 48,
    "The Creators Signature": 49,
    "Arabic Language Lessons": 50,

    // Friday Sermons
    "the Most Important Sermon GOD is Doing Everything": 12,
    "GOD is Doing Everything Rearranging Our Priorities 1987 07 No2": 13,
    "Quran vs Bible Code End of the World Revealed 2280AD 1987 07 N": 14,
    "Universal Unity Through Devotion to GOD Alone": 15,
    "the Mathematical Miracle Proves the Quran to be the Word of GO": 16,
    "Evidence is Increasing This Life is a School for the Eternal Life": 17,
    "Quran is the Only Book in the World That is Mathematically Com": 18,
    "More Evidence There is Meaning in Relations Between Numbers 19": 19,
    "The Mohammadans Discoveries by Atef and Lisa": 20,
    "the Power of Repentence the Secret of Happiness GOD Controls E": 21,
    "GOD is Doing Everything Story About Ahmed Subhy Mansour 1988 0": 22,
    "Our Purpose GOD's Kingdom vs Satan's Kingdom Abraham's Dream 1": 23,
    "Seek GOD's Kingship Over You and Everything Else Follows": 24,
    "Marriage  Importance of Love  Muhammad's Example": 25,
    "Rashad Proclaims His Messengership Abraham's Religion 1988 04": 26,
    "Rashad Explains His Messengership Details About Commandments Q": 27,
    "Natural Instinct Who is the Real You How to Find Perfect Happi": 28,
    "The Meaning of Life Discovering the Miracle Satan Created Reli": 29,
    "Who is GOD Understanding Our Universe": 30,
    "Who is Your GOD Majority of Believers Are Going to Hell 1988 1": 31,
    "Classification of Creatures Loving GOD Hell is not Enough": 32,
    "What About Previous Generations Messenger of the Covenant": 33,
    "Remember GOD Constantly Submitter vs Objector": 35,
    "Revelation of Quran to Revelation of Miracle Importance of Daw": 36,
    "Original Sin Only GOD Guides Majority of Believers Are Going t": 37,
    "Purpose of Messengers the Advent of the Pure Quran": 38,
    "Why Announce Messengership": 39,
    "Proving Every Verse Word Letter with Irrefutable Evidence": 40,
    "the Heavenly Feud the Importance of Killing the Ego": 41,
    "Proving Salat al Juma the Righteous Go Straight to Heaven": 42,
    "Miracle of Miracles al fateha Proving the Five Salat 1989 12 0": 43,
    "1989 Conference Friday Sermon": 44
};

// Also export titles cleaner map (optional, but matching keys is enough)
